version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Docker/web.dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - app
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mysql:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Docker/app.dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql